### ISSUE TITLE
wb_tree.h in src/CMakeList.txt

### ISSUE THREAD

**Issue by bosim** [libwbxml/libwbxml#51]
I have code relying on wb_tree and in never versions of this library this has been removed from  CMakeList.txt i.e. not installed when running install command. I assume it is intentional, but could you enlighten me on why it was removed?

Thanks.

**Comment by bellmich** [comment]
I reduced the interface of the library to the necessary minimum. This means the library no longer exposes the internal API. It is much easier for me to change the internals now because the binary interface does not change. This is the why (the hell he did it ;-) ).

Can you describe what you are doing with the tree code please? What's your use case? The code itself is still there. Just the interface is no longer visible.

Cheers, Michael

**Comment by bosim** [comment]
I am currently working on some code I highly modified https://github.com/bosim/akonadi-airsync and the original for wbxml processing is still there. It seems pretty straight forward to change it (from what I saw briefly). Understands 100% why you want a minimal, stable api. 

Thanks for a quick response :)

**Comment by bellmich** [comment]
If the minimal API is a problem because it is too minimal, please open a new ticket and we will discuss it.

**Comment by bosim** [comment]
Just checked what I need and it seems everything is there in wb_conv :) thanks.
